Added linq home task
onish-alex/EducationalPortal pull request #3
Opened 2021-01-08 17:21 UTC by onish-alex

2021-01-10 21:17 UTC, DaniilManita requested changes

2021-01-11 11:46 UTC, onish-alex commented on HomeTasks/LinqTask/CustomerUtilities.cs
> +            foreach (var group in oneMonthGroups)
Убрал вложенный foreach, сделал выборку через SelectMany

2021-01-11 11:47 UTC, onish-alex commented on HomeTasks/LinqTask/CustomerUtilities.cs
> +            var customerType = typeof(Customer);
убрал ссылку на тип, которая используется только один раз

2021-01-11 11:49 UTC, onish-alex commented on HomeTasks/LinqTask/CustomerUtilities.cs
> +            CustomersList.GetCustomers().DoAction(a => Console.Write("{0}, ", a.Name));
исправил

2021-01-11 11:58 UTC, DaniilManita requested changes

2021-01-11 11:58 UTC, DaniilManita commented on HomeTasks/LinqTask/CustomerUtilities.cs
> +                            .ToList()
вместо этого можно написать селект , в нем вызвать консоль и вывести на экран

2021-01-11 16:53 UTC, onish-alex commented on HomeTasks/LinqTask/CustomerUtilities.cs
> +                            .ToList()
изменил

2021-02-15 11:11 UTC, DoludaSergey approved these changes

2021-04-12 15:33 UTC, merged